stages:
  test_train_val_split:
    cmd: $VAE_PY src/pipeline/test_train_val_split.py
    deps:
    - src/pipeline/test_train_val_split.py
    outs:
    - data/intermediate/hcl_test_data.h5ad
    - data/intermediate/hcl_train_data.h5ad
    - data/intermediate/hcl_val_data.h5ad
  train_vae:
    cmd: $VAE_PY src/pipeline/train_vae.py
    deps:
      - data/intermediate/hcl_test_data.h5ad
      - data/intermediate/hcl_train_data.h5ad
      - data/intermediate/hcl_val_data.h5ad