stages:
  datasplit:
    cmd: $VAE_PY src/pipeline/datasplit.py
    deps:
    - src/pipeline/datasplit.py
    outs:
    - data/intermediate/hcl_test_data.h5ad
    - data/intermediate/hcl_train_data.h5ad
    - data/intermediate/hcl_val_data.h5ad