# 02-712 Project Pipeline Settings

[data]
subsampling = 1

[training]
latent_dimensions_initial_guess = 32
newton_temperature = 10
batch_size = 256

    [training.vae_trainer]
    # See: https://pytorch-lightning.readthedocs.io/en/latest/trainer.html
    max_epochs = 10

[simulation]
minimum_cells_per_class = 1000

[classifier]
n_hidden_layers = 2

    [classifier.training_opts]
    # See: https://pytorch-lightning.readthedocs.io/en/latest/trainer.html
    max_epochs = 1